distributable:
  url: https://zlib.net/zlib-{{version.raw}}.tar.gz
  strip-components: 1

versions:
  github: madler/zlib/tags

build:
  dependencies:
  script: |
    ./configure --prefix="{{prefix}}"
    make --jobs {{ hw.concurrency }} install

test:
  dependencies:
  script: |
    cc test.c -lz
    OUT=$(echo "$INPUT" | ./a.out | ./a.out -d)
    test "$OUT" = "$INPUT"
  env:
    INPUT: Hello, World!