distributable:
  url: https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-{{ version }}.tar.gz
  strip-components: 1

versions:
  url: https://www.bytereef.org/mpdecimal/download.html
  match: /mpdecimal-\d+\.\d+\.\d+\.tar\.gz/
  strip:
    - /mpdecimal-/
    - /.tar.gz/

build:
  dependencies:
  script: |
    ./configure --prefix={{ prefix }}
    make --jobs {{hw.concurrency}}
    make install
    rm -rf {{prefix}}/share  # docs are online
  env:
    darwin:
      # fixes a ruby-machos error
      LDFLAGS: -headerpad_max_install_names $LDFLAGS
      LDXXFLAGS: -headerpad_max_install_names $LDXXFLAGS
test:
  dependencies:
  script: |
    cc test.c -o test -lmpdec
    ./test
