distributable:
  url: https://pyyaml.org/download/libyaml/yaml-{{version}}.tar.gz
  strip-components: 1

versions:
  github: yaml/libyaml/tags
  # strip: /^v/

build:
  dependencies:
  script: |
    ./configure --prefix="{{prefix}}"
    make --jobs {{hw.concurrency}} install

test:
  dependencies:
  script: |
    cc test.c -lyaml
    ./a.out
