distributable:
  url: https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz
  strip-components: 1

versions:
  url: https://ftp.gnu.org/gnu/gperf/
  match: /gperf-(\d+\.\d+(\.\d+)?)\.tar\.gz/
  strip:
    - /gperf-/
    - /.tar.gz/

build:
  dependencies:
  script: |
    ./configure --prefix={{ prefix }}
    make --jobs {{ hw.concurrency }} install

test:
  script: echo "tea\nfoo\nbar" | gperf

provides:
  - bin/gperf