distributable:
  url: https://github.com/MathisRosenhauer/libaec/releases/download/v{{version}}/libaec-{{version}}.tar.gz
  strip-components: 1

versions:
  github: MathisRosenhauer/libaec
  strip: /^v/

build:
  dependencies:
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix="{{prefix}}"

provides:
  - bin/aec

test:
  dependencies:
  script: |
    cc -o testlibaec fixture.cpp -laec
